# Use root/example as user/password credentials
version: '3.1'
    
services:
  mongo:
    image: redis
    ports:
      - 6379:6379

  # htmx-blog:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGO_URI=mongodb://root:example@mongo:27017/

  #   depends_on:
  #     - mongo
